#include QMK_KEYBOARD_H
#include "keymap_norwegian.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(
		KC_ESC, NO_Q, NO_J, NO_K, NO_Y, NO_W,	NO_B, NO_F, NO_U, NO_MINS, NO_PLUS, NO_AE,

		NO_QUOT, LCTL_T(NO_G), LALT_T(NO_T), LSFT_T(NO_A), LGUI_T(NO_E), NO_D,	NO_R, RGUI_T(NO_I), RSFT_T(NO_O), RALT_T(NO_S), RCTL_T(NO_H), NO_OSTR,

		KC_LGUI, NO_Z, NO_X, NO_C, NO_V, NO_M,	NO_P, NO_N, NO_L, NO_COMM, NO_DOT, NO_ARNG,
		
		KC_TAB, MO(2), KC_BSPC, KC_ENT, KC_SPC, MO(1)
    ),

	[1] = LAYOUT_split_3x6_3(
		KC_LALT, KC_NO, NO_1, NO_2, NO_3, KC_BRIU,	KC_VOLU, KC_HOME, KC_UP, KC_END, KC_NO, KC_MNXT,

		KC_LCTL, LCTL_T(KC_NO), LALT_T(NO_4), LSFT_T(NO_5), LGUI_T(NO_6), NO_0,	KC_MUTE, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_MPLY,

		KC_LSFT, KC_NO, NO_7, NO_8, NO_9, KC_BRID,	KC_VOLD, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV,
		
		KC_TAB, MO(2), KC_BSPC, KC_ENT, KC_SPC, KC_TRNS
    ),

	[2] = LAYOUT_split_3x6_3(
		KC_LALT, KC_NO, NO_CIRC, NO_LABK, NO_RABK, NO_ASTR,	NO_DLR, NO_LBRC, NO_RBRC, NO_BSLS, KC_NO, KC_NO,

		KC_LCTL, NO_PERC, NO_HASH, NO_QUES, NO_EXLM, NO_DQUO, 	NO_EQL, NO_LPRN, NO_RPRN, NO_SLSH, NO_TILD, KC_NO,
		
		KC_LSFT, NO_DIAE, NO_SCLN, NO_COLN, NO_AT, NO_GRV,	NO_AMPR, NO_LCBR, NO_RCBR, NO_PIPE, NO_UNDS, KC_NO,

		KC_TAB, KC_TRNS, KC_BSPC, KC_ENT, KC_SPC, MO(1)
    )
};
